name: validate-tests
on: [pull_request]
jobs:
  validate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Validate TypeScript
        run: yarn typecheck
      - name: Run integration tests
        run: yarn jest
      - name: Lint files
        run: yarn lint
      - name: Format files
        run: yarn format
      - name: Builds project
        run: yarn build
